namespace: "epfl_si"
name: "traefik"
version: "0.6.0"
readme: "README.md"
description: "Manage Træfik in basic configurations (HTTP and HTTP/S multiplexing on standard ports)"
authors:
    - "EPFL IDEV-FSD <idev-fsd@groupes.epfl.ch>"
license:
    - "MIT"
tags:
    - traefik
repository: "https://github.com/epfl-si/ansible-collection-traefik"
dependencies:
  epfl_si.actions: ">=1.1.0"
