namespace: "epfl_si"
name: "traefik"
version: "0.1.0"
readme: "README.md"
authors:
    - "EPFL IDEV-FSD <idev-fsd@groupes.epfl.ch>"
license:
    - "MIT"
tags:
    - traefik
    - træfik
repository: "https://github.com/epfl-si/ansible-collection-traefik"
dependencies:
  epfl_si.actions: ">=0.1.1"
