- name: "{{ traefik_docker_image }} Docker image"
  community.general.docker_image:
    name: "{{ traefik_docker_image }}"
    state: present
    source: pull

- name: Start or restart traefik container
  community.general.docker_container:
    name: "{{ traefik_container_name }}"
    image: "{{ traefik_docker_image }}"
    command:
      --api
    state: started
    restart: "{{ _traefik_restart_notified | default(false) | bool }}"
    restart_policy: "{{ traefik_container_restart_policy }}"
    log_driver: json-file
    log_options:
      max-size: "{{ traefik_log_max_size }}"
      max-file: "{{ traefik_log_rotate_keep_number | string }}"
    mounts: >-
      {{ mounts_always + mount_docker_sock
         if traefik_use_docker_labels
         else mounts_always }}
    ports: "{{ _traefik_external_ports }}"
    container_default_behavior: no_defaults
    networks_cli_compatible: no
    networks: "{{ traefik_docker_networks }}"  ## In addition to the default one (bridge),
                                        ## since we are not setting purge_networks
  vars:
    mounts_always:
    - type: bind
      source: "{{ traefik_static_config_file_path }}"
      target: /etc/traefik/traefik.yml
    - type: bind
      source: "{{ traefik_dynamic_config_dir }}"
      target: /etc/traefik/dynamic
    - type: bind
      source: "{{ traefik_ssl_certs_location }}"
      target: /etc/traefik/certs
    mount_docker_sock:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
